from datetime import timedelta
from decimal import Decimal
from unittest.mock import patch

from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from accounts.models import User
from orders.models import DiscountCode, Order, Service


class DashboardPickupTests(TestCase):
    def setUp(self):
        self.user = User.objects.create_user(
            email="customer@example.com",
            full_name="Test Customer",
            phone="",
        )
        self.service = Service.objects.create(
            name="Restoration",
            price=Decimal("15000"),
            is_active=True,
        )
        self.client.force_login(self.user)

    def test_dashboard_contains_working_pickup_form(self):
        response = self.client.get(reverse("orders:dashboard"))

        self.assertContains(response, 'id="dashboard-pickup-form"')
        self.assertContains(response, 'name="pickup_date"')
        self.assertContains(response, 'type="submit" class="submit-btn"')

    @patch("orders.views.send_admin_notification_task.delay")
    @patch("orders.views.send_order_confirmation_email_task.delay")
    def test_authenticated_pickup_creates_order_and_returns_to_dashboard(
        self, confirmation_delay, admin_delay
    ):
        discount = DiscountCode.objects.create(
            code="SNKYLN",
            discount_amount=Decimal("2000"),
        )

        response = self.client.post(
            reverse("orders:create_order"),
            {
                # Authenticated identity must not be replaceable from the browser.
                "full_name": "Tampered Name",
                "email": "someone-else@example.com",
                "phone": "+2340000000000",
                "address": "12 Admiralty Way, Lekki",
                "location": "island",
                "pickup_date": (timezone.localdate() + timedelta(days=1)).isoformat(),
                "instructions": "Handle with care",
                "discount_code": "SNKYLN",
                # This is the payload generated by services-dash.js.
                "services": self.service.name,
                "service_quantities[]": ["2"],
            },
        )

        self.assertRedirects(response, reverse("orders:dashboard"))
        order = Order.objects.get()
        self.assertEqual(order.user, self.user)
        self.assertEqual(order.email, self.user.email)
        self.assertEqual(order.full_name, self.user.full_name)
        self.assertEqual(order.phone, "")
        self.assertEqual(order.service_type, self.service.name)
        self.assertEqual(order.quantity, 2)
        self.assertEqual(order.subtotal, Decimal("30000"))
        self.assertEqual(order.discount_amount, Decimal("2000"))
        self.assertEqual(order.items.get().quantity, 2)

        discount.refresh_from_db()
        self.assertEqual(discount.times_used, 1)
        confirmation_delay.assert_called_once_with(order.id)
        admin_delay.assert_called_once_with(order.id)
