# Generated by Django 5.0.4 on 2026-04-26 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Service description for customers')),
                ('price', models.DecimalField(decimal_places=2, help_text='Base price for this service', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Display this service on website')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display on frontend (lower = first)')),
                ('icon', models.CharField(blank=True, help_text='CSS icon class', max_length=50)),
                ('estimated_duration', models.CharField(blank=True, help_text="e.g., '2-3 hours'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text='Service name at time of order', max_length=100)),
                ('price_at_order', models.DecimalField(decimal_places=2, help_text='Price when order was placed', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='price_at_order * quantity', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.service')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
